Western US map yai
For pogo parentals and hybrid points
========================================================



Packages
```{r}
library(png)
library(RgoogleMaps)
library(sp)
library(raster)
library(dismo)
library(foreign)
library(grid)
library(lattice)
library(maptools)
library(rgdal)
library(maps)
library(mapdata)
library(ggplot2)
library(XML)

```

My script, plotting pogo/hybrid sites on map and also precipitation     

```{r}
# read in data
d<-read.csv("Coordinates_Sites.csv",header=TRUE);d

#get worldclim data
hap <- getData("worldclim", var = "bio", res = 2.5)
names(hap)
```
BIO12 = Annual Precipitation   


```{r}
# Extract climate values for site lon/lat from bioclim data
dbio1 <- extract(hap, d[, c("lon", "lat")])

dbio1 <- cbind(d, dbio1[,12])

colnames(dbio1)[7] <- "MAPx10"
dbio1$MAP <- dbio1$MAPx10/10
head(dbio1)
dude<-c(rep("orange",5),rep("green",4),rep("blue",6),rep("red",4));dude

p<-c(17,16)
shape<-p[as.integer(dbio1$caste)];shape

cbind(dbio1,shape)
```

```{r}
plot(hap,12,xlim=c(-115,-95),ylim=c(24,36),las=1,col=colorRampPalette(c("white","black"))(255),legend=FALSE,axes=F,box=FALSE,main="") #black white
#plot(hap,xlim=c(-120,-92),ylim=c(23,37.5),las=1,legend=FALSE) # colored
map("worldHires",c("Mexico","USA"),add=TRUE,xlim=c(-115,-95),ylim=c(24,36))
map("state",c("Nevada","Texas","California","New Mexico","Arizona"),add=TRUE)
points(dbio1$lon,dbio1$lat,cex=1,pch=shape,col=dude)
text(dbio1$lon,dbio1$lat+.5,labels=dbio1$point,cex=.8,col=dude)

#getting rid of anything outside of the plot I want
rect(-120,15,-115,60,col="white",border=FALSE)
rect(-95,15,-80,60,col="white",border=FALSE)
legend(-114,26,c("H lineage","J lineage","P. rugosus","P. barbatus"),pch=16,col=c("green","blue","red","orange"),cex=1.1,text.font=3,horiz=T)

```
